name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to get all tags

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate next tag
        id: next_tag
        run: |
          tag=${{ steps.get_tag.outputs.tag }}
          IFS='.' read -r major minor patch <<<"${tag#v}"
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "Next tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag and push
        env:
          TAG: ${{ steps.next_tag.outputs.new_tag }}
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push origin "$TAG"
