jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Build Linux and macOS binaries
        if: matrix.os == 'ubuntu-latest'
        run: |
          GOOS=linux GOARCH=amd64 go build -o json-diff-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o json-diff-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o json-diff-darwin-arm64

      - name: Build Windows binary
        if: matrix.os == 'windows-latest'
        run: |
          GOOS=windows GOARCH=amd64 go build -o json-diff-windows-amd64.exe

      - name: Install Inno Setup
        if: matrix.os == 'windows-latest'
        run: |
          choco install innosetup -y

      - name: Create Inno Setup script
        if: matrix.os == 'windows-latest'
        run: |
          echo '[Setup]' > json-diff.iss
          echo 'AppName=json-diff' >> json-diff.iss
          echo 'AppVersion=1.0.0' >> json-diff.iss
          echo 'DefaultDirName={pf}\json-diff' >> json-diff.iss
          echo 'DefaultGroupName=json-diff' >> json-diff.iss
          echo 'AllowNoIcons=yes' >> json-diff.iss
          echo 'OutputDir=.' >> json-diff.iss
          echo 'OutputBaseFilename=json-diff-installer' >> json-diff.iss
          echo 'Compression=lzma' >> json-diff.iss
          echo 'SolidCompression=yes' >> json-diff.iss
          echo '[Files]' >> json-diff.iss
          echo 'Source: "json-diff-windows-amd64.exe"; DestDir: "{app}"; Flags: ignoreversion' >> json-diff.iss
          echo '[Icons]' >> json-diff.iss
          echo 'Name: "{group}\json-diff"; Filename: "{app}\json-diff-windows-amd64.exe"' >> json-diff.iss
          echo 'Name: "{group}\Uninstall json-diff"; Filename: "{uninstallexe}"' >> json-diff.iss
          echo '[Run]' >> json-diff.iss
          echo 'Filename: "{app}\json-diff-windows-amd64.exe"; Description: "Run json-diff"; Flags: nowait postinstall skipifsilent' >> json-diff.iss
          echo '[Registry]' >> json-diff.iss
          echo 'Root: HKLM; Subkey: "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype' >> json-diff.iss

      - name: Generate installer
        if: matrix.os == 'windows-latest'
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" json-diff.iss

      # Upload all binaries and installer only once (e.g., from ubuntu or windows)
      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            json-diff-linux-amd64
            json-diff-darwin-amd64
            json-diff-darwin-arm64
            json-diff-windows-amd64.exe
            json-diff-installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
