name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Build Linux and macOS binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o json-diff-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o json-diff-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o json-diff-darwin-arm64

      - name: Upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            json-diff-linux-amd64
            json-diff-darwin-amd64
            json-diff-darwin-arm64

  windows-build:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Download built binaries artifact
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./  # or wherever you want

      - name: Build Windows binary
        shell: pwsh
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o json-diff-windows-amd64.exe

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create Inno Setup script
        shell: pwsh
        run: |
          @"
[Setup]
AppName=json-diff
AppVersion=1.0.0
DefaultDirName={pf}\json-diff
DefaultGroupName=json-diff
AllowNoIcons=yes
OutputDir=.
OutputBaseFilename=json-diff-installer
Compression=lzma
SolidCompression=yes

[Files]
Source: "json-diff-windows-amd64.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\json-diff"; Filename: "{app}\json-diff-windows-amd64.exe"
Name: "{group}\Uninstall json-diff"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\json-diff-windows-amd64.exe"; Description: "Run json-diff"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKLM; Subkey: "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype
"@ | Out-File -Encoding ASCII json-diff.iss

      - name: Generate installer
        shell: pwsh
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" json-diff.iss'

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            json-diff-linux-amd64
            json-diff-darwin-amd64
            json-diff-darwin-arm64
            json-diff-windows-amd64.exe
            json-diff-installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
